name: InfraestruturaMSA

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # IP DA MAQUINA LOCAL
      KC_HOSTNAME: <IP>
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=mysql-db
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=zabbix
      - ZBX_CACHESIZE=256M
    ports:
      - "10051:10051"
    depends_on:
      - mysql-db
    restart: always

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=mysql-db
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=zabbix
      - PHP_TZ=America/Sao_Paulo
    ports:
      - "8090:8080"
    depends_on:
      - mysql-db
      - zabbix-server
    restart: always